questions =  [
    {"id": 0, "question": "For the SMC to thrive, it is necessary for new managers to be promoted actively.", "effects": {"right": -1}},
    {"id": 1, "question": "Older mappers are more worthy of being managers than newer mappers", "effects": {"right": 1}},
    {"id": 2, "question": "Looking at history, half-mappers are more likely to start conflict and therefore should not be trusted.", "effects": {"right": 1}},
    {"id": 3, "question": "A newer mapper is more likely to start any sort of war or conflict than an older mapper": {"right": 1}},
    {"id": 4, "question": "The more members the SMC gets, the more likely it is for more wars to break out", "effects": {"right": 1}},
    {"id": 5, "question": "It would make sense for newer mappers to be banned from Discord or Fandom, as that is where newer mappers will often begin war.", "effects": {"right": 1}},
    {"id": 6, "question": "Most new mappers are untrustworthy.", "effects": {"right": 2}},
    {"id": 7, "question": "We must not trust any new mappers until they can prove to older mappers that they are not cloutchasers.", "effects": {"right": 1}},
    {"id": 8, "question": "The idea of a Great Divide could be beneficial to the SMC in a way if older mappers were to win.", "effects": {"right": 1}},{"auth": 1}},
    {"id": 9, "question": "A 'lockdown' of the SMC would be necessary in the event of a Fourth Cloutchaser War or a Great Divide-based war.", "effects": {"right": 1}},
    {"id": 10, "question": "Instantly accusing new mappers of being alts is not a good idea and could do harm to that mapper and their relations to the SMC.", "effects": {"right": -1}},
    {"id": 11, "question": "A war based on a divide between older mappers and newer mappers would eventually be the downfall of the SMC.": {"right": -1}},
    {"id": 12, "question": "Half-mappers and observers should have the same amount of trust as full mappers.", "effects": {"right": -1}},
    {"id": 13, "question": "Mappers who were formerly cloutchasers or accused cloutchasers should recieve full trust from the SMC, as they have hopefully changed.", "effects": {"right": -1}},
    {"id": 14, "question": "Any mappers asking to join should be allowed in with no questioning.", "effects": {"right": -3}},
    {"id": 15, "question": "Some SMC wars may be justified, depending on the subject.", "effects": {"auth": 1}},
    {"id": 16, "question": "In the end, wars in the SMC will do no long-term harm on members.", "effects": {"auth": 1}},
    {"id": 17, "question": "If a war based on an issue in the SMC that I felt strongly about broke out, I would likely join.", "effects": {"auth": 1}},
    {"id": 18, "question": "If a war broke out based on an action of my friend, I would join on my friend's side to help them.", "effects": {"auth": 1}},
    {"id": 19, "question": "Joke wars are ultimately harmless and the hate towards them is unjustified.", "effects": {"auth": 1}},
    {"id": 20, "question": "Some wars in the SMC will ultimately have a good result in the end.", "effects": {"auth": 1}},
    {"id": 21, "question": "I frequently engage in arguments with other mappers.", "effects": {"auth": 1}},
    {"id": 22, "question": "I have recently engaged in a war with other mappers.", "effects": {"auth": 1}},
    {"id": 23, "question": "No war in SMC history has been justified; and none likely ever will.", "effects": {"auth": -1}},
    {"id": 24, "question": "Even arguments and debates in the SMC that are not justified, as they also leave harm to the members involved.", "effects": {"auth": -1}},
    {"id": 25, "question": "I have never engaged in an SMC war.", "effects": {"auth": -2}},
    {"id": 26, "question": "The less influence of managers and admins in the SMC, the freer the mappers.", "effects": {"auth": -1}},
    {"id": 27, "question": "The Scratch Mapping Community would ultimately be better off without war.", "effects": {"auth": -1}},
    {"id": 28, "question": "I would never join in on a fourth cloutchaser war or mapper war.", "effects": {"auth": -1}},
    {"id": 29, "question": "The entire SMC should not fight, as the community all shares one common interest.", "effects": {"auth": -1}},
];
